name: Build and Deploy email-service

on:
  push:
    branches:
        - 'main'
    tags:
        - 'v*'

env:
  DOCKER_USERNAME: leonardorothier
  IMAGE: leonardorothier/email-service
  
jobs:
    build_email_service:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ env.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.IMAGE }}
                tags: |
                  type=raw,value=latest,enable={{is_default_branch}}

                  type=ref,event=tag

            
            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}