name: Build and Deploy email-service

on:
  push:
    branches:
        - 'main'
    tags:
        - 'v*'

env:
  DOCKER_USERNAME: leonardorothier
  IMAGE: leonardorothier/email-service
  
jobs:
    build_email_service:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ env.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.IMAGE }}
                tags: |
                  type=raw,value=latest,enable={{is_default_branch}}

                  type=ref,event=tag

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
    
    deploy_email_service:
      if: contains(github.ref, 'main')
      needs: build_email_service
      runs-on: ubuntu-latest
      env:
        CONTAINER_NAME: email-service
      steps:
        - name: Deploy to Server via SSH
          uses: appleboy/ssh-action@v1.2.2
          with:
            host: ${{ secrets.ATLAS_HOST }}
            port: 2223
            username: github
            key: ${{ secrets.ATLAS_PRIVATE_KEY }}
            script: |
              docker pull ${{env.IMAGE}}:latest
              docker stop ${{env.CONTAINER_NAME}} || true
              docker rm ${{env.CONTAINER_NAME}} || true
              docker run -d -p 8080:8080 --name=${{env.CONTAINER_NAME}} \
                -e SENDER_PROVIDER=${{ vars.SENDER_PROVIDER }} \
                -e SENDER_NAMES=${{ vars.SENDER_NAMES }} \
                -e SENDER_COMPRAS_EMAIL=${{ vars.SENDER_COMPRAS_EMAIL }} -e SENDER_FINANCEIRO_EMAIL=${{ vars.SENDER_FINANCEIRO_EMAIL }} -e SENDER_CONTROLE_EMAIL=${{ vars.SENDER_CONTROLE_EMAIL }} \
                -e SERVICE_ACCOUNT_EMAIL=${{ vars.SERVICE_ACCOUNT_EMAIL }} -e SERVICE_ACCOUNT_PASS=${{ secrets.SERVICE_ACCOUNT_PASS }} \
                ${{env.IMAGE}}:latest

              # clean: removing dangling images  
              docker image prune -af